[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
board_build.filesystem = littlefs
framework = arduino
monitor_speed = 115200
upload_speed = 921600
build_flags = 
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DARDUINO_LITTLEFS_ENABLE
lib_deps = 
  WiFi
  tzapu/WiFiManager@^2.0.17
  bblanchon/ArduinoJson
  OneWire
  DallasTemperature
  paulstoffregen/OneWire@^2.3.7
  milesburton/DallasTemperature@^3.11.0
  olikraus/U8g2